preload = ["@ecopages/bun-postcss-loader", "@ecopages/bun-mdx-kitajs-loader"]

[test]
preload = ["@ecopages/bun-postcss-loader", "@ecopages/bun-mdx-kitajs-loader"]
[install.scopes]
"@jsr" = "https://npm.jsr.io"
