preload = [
  "@ecopages/core/loaders/inline-postcss.loader.js",
  "@ecopages/core/loaders/mdx.loader.js",
]

[test]
preload = [
  "@ecopages/core/loaders/inline-postcss.loader.js",
  "@ecopages/core/loaders/mdx.loader.js",
]
