preload = [
  "@ecopages/core/src/loaders/inline-postcss.loader.ts",
  "@ecopages/core/src/loaders/mdx.loader.ts",
]

[test]
preload = [
  "@ecopages/core/src/loaders/inline-postcss.loader.ts",
  "@ecopages/core/src/loaders/mdx.loader.ts",
]
