preload = [
  "@ecopages/core/src/loaders/postcss.loader.js",
  "@ecopages/core/src/loaders/mdx.loader.js",
]

[test]
preload = [
  "@ecopages/core/src/loaders/postcss.loader.js",
  "@ecopages/core/src/loaders/mdx.loader.js",
]
